=== hoiwanjohnlouis/nyu-archive/nyu-scps-201201-Java2-x52.9271-archive/java2_session4/java2_demo4/schema_specific/6.06/Address.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Listing 6.06 complex datatype with global element and attribute-->
<!DOCTYPE xs:schema PUBLIC "-//W3C//DTD XMLSCHEMA 200102//EN" 'http://www.w3.org/2001/XMLSchema.dtd'>
<xs:schema targetNamespace="http://www.nyu.edu/jws/Address" xmlns:addr="http://www.nyu.edu/jws/Address" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="USAddress">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="category" type="xs:string"/>
		<xs:attribute ref="addr:language"/>
	</xs:complexType>
	<xs:attribute name="language" type="xs:string"/>
	<xs:element name="address" type="addr:USAddress"/>
</xs:schema>

=== hoiwanjohnlouis/nyu-archive/nyu-scps-201201-Java2-x52.9271-archive/java2_session4/java2_demo4/schema_specific/6.10/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Listing 6.10 valid global element has namespace, local elements do not-->
<addr:address addr:language="us-en" category="work" xmlns:addr="http://www.nyu.edu/jws/Address" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nyu.edu/jws/Address ../6.08/Address.xsd">
	<addr:name>John Smith</addr:name>
	<addr:name>John1 Smith1</addr:name>
	<addr:name>John2 Smith2</addr:name>
	<addr:name>John3 Smith3</addr:name>
	<addr:name>John4 Smith4</addr:name>
	<addr:street>121 River Street</addr:street>
	<addr:street>89 River Street</addr:street>
	<addr:city>Hoboken</addr:city>
	<addr:state>NJ</addr:state>
	<addr:zip>07030</addr:zip>
</addr:address>
