=== hoiwanjohnlouis/nyu-archive/nyu-scps-201201-Java2-x52.9271-archive/java2_session4/java2_demo4/schema_specific/6.17/Address.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Listing 6.17  inheritance <InternationalAddress> extends <Address>-->
<!DOCTYPE xs:schema PUBLIC "-//W3C//DTD XMLSCHEMA 200102//EN" 'http://www.w3.org/2001/XMLSchema.dtd'>
<xs:schema xmlns:tns="http://www.nyu.edu/jws/Address" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.nyu.edu/jws/Address" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:attribute name="language" type="xs:string"/>
	<xs:element name="address" type="tns:Address"/>
	<xs:element name="internationaladdress" type="tns:InternationalAddress"/>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="street" type="xs:string" maxOccurs="3"/>
			<xs:choice>
				<xs:element name="apartment" type="xs:string"/>
				<xs:element name="floor" type="xs:string"/>
			</xs:choice>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="category" type="xs:string" use="optional" default="home"/>
		<xs:attribute ref="tns:language" use="required"/>
	</xs:complexType>
	<xs:complexType name="InternationalAddress">
		<xs:complexContent>
			<xs:extension base="tns:Address">
				<xs:sequence>
					<xs:element name="country" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="countrycode" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== hoiwanjohnlouis/nyu-archive/nyu-scps-201201-Java2-x52.9271-archive/java2_session4/java2_demo4/schema_specific/6.18A/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Listing 6.18A valid since it follows <InternationalAddress> schema which extends <Address> schema-->
<addr:internationaladdress addr:language="us-en" addr:category="work" addr:countrycode="usa" xmlns:addr="http://www.nyu.edu/jws/Address" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nyu.edu/jws/Address ../6.17/Address.xsd">
	<addr:street>Marsh ETG Department</addr:street>
	<addr:street>121 River Street</addr:street>
	<addr:floor>4th</addr:floor>
	<addr:city>Hoboken</addr:city>
	<addr:state>NJ</addr:state>
	<addr:zip>07030</addr:zip>
	<addr:country>United States of America</addr:country>
</addr:internationaladdress>

=== hoiwanjohnlouis/nyu-archive/nyu-scps-201201-Java2-x52.9271-archive/java2_session4/java2_demo4/schema_specific/6.24/address.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Listing 6.24 valid address since it refers to <internationaladdress> element which uses concrete datatype--><addr:internationaladdress addr:language="us-en" addr:countrycode="ban" xmlns:addr="http://www.nyu.edu/jws/Address" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nyu.edu/jws/Address ../6.23/Address.xsd">	<addr:name>John Smith</addr:name>	<addr:street>16 Mirpur Road</addr:street>	<addr:street>Shamoli</addr:street>	<addr:apartment>2B</addr:apartment>	<addr:city>Dhaka</addr:city>	<addr:state></addr:state>	<addr:zip></addr:zip>	<addr:country>Bangladesh</addr:country></addr:internationaladdress>
